### ISSUE TITLE
Pedro Mesmer

### ISSUE THREAD

**Issue by pedromesmer** [TI-RN/profissionais#5]
**Nome:** Pedro Mesmer
**E-mail:** pedro_mesmer@hotmail.com
**Telefone:** (84) 987215893
**LinkedIn:** www.linkedin.com/in/pedromesmer

### Conhecimentos técnicos
- **Linguagens de programação:** C++, JavaScript, Java, Python
- **Bancos de Dados:** SQLite
- **Automação**: Arduino, Raspberry, Domótica
- **Sistemas Operacionais:** Linux, Windows
- **Certificações:**  698: Installing and Configuring Windows 10

### Formação acadêmica
- Técnico em Manutenção e Suporte em Informática - IFRN - 2017
- Graduação em Engenharia da Computação - UnP

**Comment by joelrlneto** [comment]
Bom dia, @pedromesmer .
Favor indicar as labels referentes à sua atuação (cidade, área técnica e tipo de contratação).
Preferencialmente, especificar qual é a certificação de Windows 10.
