### ISSUE TITLE
Werdeles Soares

### ISSUE THREAD

**Issue by werdelesmarcio** [TI-RN/profissionais#7]
**Nome:** Werdeles Marcio de C. Soares
**E-mail:** werdelesmarcio@hotmail.com
**Telefone(s):** (84) 98605-8654
**LinkedIn:** [https://www.linkedin.com/in/werdeles-soares/](https://www.linkedin.com/in/werdeles-soares/)

### Conhecimentos técnicos

**Linguagens de programação:** C, C#, Python
**Bancos de Dados:** MySQL, SQLServer
**Ferramentas:** GLPI, Raspberry, Grafana
**Sistemas Operacionais:** Linux, Windows, MacOS

### Formação acadêmica
- Bacharelado em Tecnologia da Informação - Ênfase em Engenharia de Softwares - UFRN - Cursando

**Comment by joelrlneto** [comment]
Bom dia, @werdelesmarcio .

Por favor, informe aqui as cidades de atuação, áreas técnicas e formas de contratação (PF ou PJ) para adicionarmos os labels.

**Comment by werdelesmarcio** [comment]
Natal, Recife, suporte técnico, desenvolvimento, técnico em TI, pf e pj.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
